on:
    push:
        branches:
            - main
jobs: 
    build:
        runs-on: ubuntu-latest



        steps:
            - name: 'print content'
              run: ls
        
            - uses: actions/checkout@v3
            
            - name: 'print content'
              run: ls

